version: '2'

services:
  web:
    restart: always
    build:
      context: ../
      dockerfile: demo/configs/uwsgi/Dockerfile
    env_file: configs/env
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - pgbouncer:pgbouncer
    depends_on:
      - pgbouncer

  postgres:
    restart: always
    env_file: configs/env
    image: postgres:10
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgbouncer:
    restart: always
    image: brainsam/pgbouncer:latest
    expose:
      - "6432"
    links:
      - postgres:postgres
    env_file: configs/pgbouncer_env
    depends_on:
      - postgres